version: 2
jobs:
  build1:
    docker:
    
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      - save_cache:
        key: v1 -repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - ~/circleci-demo-workflows
    steps:
      - persist_to_workspace:
        root: workspace
        paths:
          - echo-output

  build2:
    docker:
    
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - restore_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
        name: テストの実行
        command: make test
    steps:
      - attach_workspace:
        at: /tmp/workspace
        
  build3:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - restore_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
        name: アセットのプリコンパイル
        command: bundle exec rake assets:precompile
    steps:
      - store_artifacts:
        path: /tmp/artifact-1
        destination: artifact-file
        
workflows:
  version: 2
  build_and_test:
    jobs:
      - build1
      - build2:
        requires:
          - build1
      - build3:
        requires:
          - build1
